config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :trips do
    resources :bookings, only: %i[new create show]
  end
  resources :bookings, except: %i[new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :start_point, :end_point, :capacity, presence: true

  def passengers_count
    self.bookings.map { |b| b.passengers if b.status == "Accepted" }.compact.sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips, through: :bookings
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name last_name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @trips = Trip.all
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      sql_query = " \
        trips.starting_point @@ :query \
        OR trips.end_point @@ :query \
      "
      @trips = policy_scope(Trip).where(sql_query, query: "%#{params[:query]}%")
    else
      @trips = policy_scope(Trip).order(created_at: :desc)
    end
  end

  def show
  end

  def new
    @trip = Trip.new
    authorize @trip
  end

  def edit
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    authorize @trip

    if @trip.save
      redirect_to @trip, notice: 'trip was successfully created.'
    else
      render :new
    end
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip, notice: 'trip was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @trip.destroy
      redirect_to trips_url, notice: 'trip was successfully destroyed.'
    else
      render :root
    end
  end

  def my_trips
    @trips = policy_scope(Trip).where(user: current_user)
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
    authorize @trip
  end

  def trip_params
    params.require(:trip).permit(:start_point, :end_point, :departure_time, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeLlevoV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# BANNER %>
<div class="banner text-center">
  <h1>Ahorra en tus viajes del día a día</h1>
  <div class="form">
    <h3>Search bar</h3>
  </div>
</div>

<%# BENEFICIOS %>
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-4 text-center">
      <h4>Miles de viajes baratos</h4>
      <p>Vayas donde vayas, encuentra tu viaje ideal a un precio muy bajo.</p>
    </div>
    <div class="col-12 col-sm-4 text-center">
      <h4>Viaja seguro y tranquilo</h4>
      <p>Para nosotros es muy importante conocer a nuestros usuarios. Por eso, examinamos atentamente las opiniones y los perfiles de nuestros usuarios para que sepas con quién vas a viajar. Puedes reservar tu próximo viaje con total seguridad y tranquilidad.</p>
    </div>
    <div class="col-12 col-sm-4 text-center">
      <h4>¡Busca, elige y a viajar!</h4>
      <p>¡Reservar un viaje es más fácil que nunca! Gracias a nuestra sencilla aplicación y a su potente tecnología, podrás reservar un viaje cerca de ti en minutos.</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%# LOGO %>
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "car.jpeg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# BUSCAR %>
          <li class="nav-item active">
            <%= link_to "🔍 Buscar", "#", class: "nav-link" %>
          </li>

          <%# PUBLICAR %>
          <li class="nav-item">
            <%= link_to "🚙 Publicar viaje", "#", class: "nav-link" %>
          </li>

          <%# USUARIO %>
          <li class="nav-item dropdown">
            <%= current_user.name %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mensajes", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_trip_card.html.erb
<div class="tripCard">
  <div class="tripCard-mainContainer">
    <%# info itinerario %>
    <div class="tripCard-main">
      <%# destinos %>
      <div class="tripCard-itinerary">
        <%# fecha %>
        <div style="margin-left: 30px">
          <span><%= trip.departure_time.strftime('%A %e, %B - %H:%M') %></span>
        </div>
        <%# partida %>
        <div class="inicio">
          <div class="palito">
            <div class="palito-spacio"></div>
            <div class="palito-pelota">
              <div class="palito-pelota-interna"></div>
            </div>
            <div class="palito-bajo"></div>
          </div>
          <div class="inicio-info">
            <span><strong>🚙 </strong><%= trip.start_point %></span>
            <span><%= '<i class="fas fa-user" style="color: #36AE7C; margin-right: 4px;" ></i>'.html_safe * (trip.capacity - trip.passengers_count) %> <%= '<i class="fas fa-user" style="color: #EB5353; margin-right: 4px;" ></i>'.html_safe * trip.passengers_count %></span>
          </div>
        </div>
        <%# llegada %>
        <div class="destino">
          <div class="palito">
            <div class="palito-pelota">
              <div class="palito-pelota-interna"></div>
            </div>
            <div class="palito-bajo"></div>
            <div class="palito-spacio"></div>
          </div>
          <div>
            <span><strong>🏁 </strong><%= trip.end_point %></span>
          </div>
        </div>
      </div>
      <%# precio %>
      <div class="tripCard-price">
        <span>$6.000</span>
      </div>
    </div>
    <%# info drive %>
    <div class="tripCard-driver">
      <%# izquierda %>
      <div class="tripCard-driver-leftWrapper">
        <%# foto %>
        <span>
          <div>
            <img src="https://d2kwny77wxvuie.cloudfront.net/user/DMbf7B2kRhiyhQhdNfq97Q/thumbnail_144x144.jpeg" alt="Fabrizio Oyarce" class="tripCard-avatar">
          </div>
        </span>
        <%# nombre %>
        <div class="tripCard-driver-info">
          <span><%= trip.user.full_name %></span>
          ⭐⭐⭐
        </div>
      </div>
      <%# derecha %>
      <div class="tripCard-driver-rightWrapper">
        <ul>
          <li title="Aceptación automática"><img src="https://cdn.blablacar.com/search/images/spa/filters/automatic_approval.svg" height="24" width="24"></li>
          <li title="Máx. 2 personas atrás"><img src="https://cdn.blablacar.com/search/images/spa/filters/two_max_in_the_back.svg" height="24" width="24"></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>
  <ul>
    <% if @trip.errors.any?%>
      <% @trip.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>

  <div class="form-inputs">
    <%= f.input :start_point, required: true %>
    <%= f.input :end_point, required: true %>
    <%= f.input :departure_time %>
    <%= f.input :capacity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success" %>
  </div>
<% end %>

app/views/trips/index.html.erb
<div class="m-3 justify-content-center text-center">
  <div class="d-flex justify-content-center m-3">

    <%# Barra de búsqueda %>
    <div>
      <%= form_tag trips_path, class:"d-flex", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control me-2",
          placeholder: "Find a trip"%>
      <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>

    <%# Boton crear viaje %>
    <div>
      <%= link_to 'Publicar Viaje', new_trip_path, class:"btn btn-primary ms-2" %>
    </div>
  </div>
  <h1>Viajes disponibles</h1>
</div>

<div class="container">
  <% @trips.each do |trip| %>
    <% if (trip.capacity - trip.passengers_count) > 0 %>
      <%= render 'shared/trip_card', trip: trip %>
    <% end %>
  <% end %>
</div>

app/views/trips/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>Nuevo Viaje</h1>

      <%= render 'form', trip: @trip %>

      <%= link_to 'Back', trips_path, class:"btn btn-info"%>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div class="container">
  <div class="row justify-content-center m-5">
    <div class="col-md-6 card">
      <div class="card-body">
        <h3 class="card-title">Desde: <%= @trip.start_point %></h3>
        <h3 class="card-title">Hacia: <%= @trip.end_point %></h3>
        <ul class="style-list">
          <li>Pasajeros: <%= '<i class="fas fa-user" style="color: #36AE7C; margin-right: 4px;" ></i>'.html_safe * (@trip.capacity - @trip.passengers_count) %> <%= '<i class="fas fa-user" style="color: #EB5353; margin-right: 4px;" ></i>'.html_safe * @trip.passengers_count %> </li>
          <li>Partida: <%= time_tag(@trip.departure_time) %></li>
        </ul>
        <h5>Conductor: <small><%= @trip.user.name %> <%= @trip.user.last_name %></small> </h5>
        <div class="text-center mt-4">
          <% if policy(@trip).edit? %>
            <%= link_to 'Edit', edit_trip_path, class: "btn btn-secondary"%>
          <% end %>
          <% if policy(@trip).destroy? %>
            <%= link_to 'Destroy', @trip, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary" %>
          <% end %>
          <% if !policy(@trip).edit? %>
            <%= link_to 'Book', new_trip_booking_path(@trip), class: "btn btn-secondary"%>
          <% end %>
          <%= link_to 'Back', trips_path, class:"btn btn-secondary"%>
        </div>
      </div>
    </div>
  </div>
</div>